AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Bookmark Application Backend

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:

  # -----------------------------
  # DynamoDB Table
  # -----------------------------
  BookmarkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Bookmarks
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: bookmarkId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: bookmarkId
          KeyType: RANGE

  # -----------------------------
  # API Gateway with Cognito Auth
  # -----------------------------
  BookmarkApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: BookmarkApi
      StageName: prod
      Cors:
        AllowOrigin: "'http://localhost:3000'"
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:us-east-1:492267599260:userpool/us-east-1_y7SR1nUQN
  # -----------------------------
  # Lambda: Create Bookmark
  # POST /bookmarks
  # -----------------------------
  CreateBookmarkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/createBookmark/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref BookmarkTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookmarkTable
      Events:
        CreateBookmarkApi:
          Type: Api
          Properties:
            RestApiId: !Ref BookmarkApi
            Path: /bookmarks
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  # -----------------------------
  # Lambda: Get Bookmarks
  # GET /bookmarks
  # -----------------------------
  GetBookmarksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/getBookmarks/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref BookmarkTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BookmarkTable
      Events:
        GetBookmarksApi:
          Type: Api
          Properties:
            RestApiId: !Ref BookmarkApi
            Path: /bookmarks
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${BookmarkApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
